// types.ts
import { z } from 'zod';

export const VehicleInspectionSchema = z.object({
  vehicleId: z.string().min(1, "Placa é obrigatória"),
  crlvEmDia: z.boolean(),
  fotoCRLV: z.string().optional(),
  certificadoTacografoEmDia: z.boolean(),
  fotoTacografo: z.string().optional(),
  nivelAgua: z.string().optional(),
  fotoNivelAgua: z.string().optional(),
  nivelOleo: z.string().optional(),
  situacaoPneus: z.string().optional(),
  fotosPneusBom: z.string().optional(),
  motivoPneuRuim: z.string().optional(),
  fotosPneusRuim: z.string().optional(),
  pneuFurado: z.boolean().optional(),
  fotoPneuFurado: z.string().optional(),
  descricaoPneuFurado: z.string().optional(),
  avariasCabine: z.boolean(),
  descricaoAvariasCabine: z.string().optional(),
  fotosAvariasCabine: z.string().optional(),
  bauPossuiAvarias: z.boolean(),
  descricaoAvariasBau: z.string().optional(),
  fotosAvariasBau: z.string().optional(),
  funcionamentoParteEletrica: z.boolean(),
  motivoParteEletricaRuim: z.string().optional(),
  fotosParteEletricaRuim: z.string().optional(),
  sugestao: z.string().optional(),
  userId: z.string().optional()
});

export type VehicleInspectionForm = z.infer<typeof VehicleInspectionSchema>;

export const initialFormState: VehicleInspectionForm = {
  crlvEmDia: true,
  fotoCRLV: '',
  certificadoTacografoEmDia: true,
  fotoTacografo: '',
  nivelAgua: 'Normal',
  fotoNivelAgua: '',
  nivelOleo: 'Normal',
  situacaoPneus: 'Bom',
  fotosPneusBom: '',
  motivoPneuRuim: '',
  fotosPneusRuim: '',
  pneuFurado: false,
  fotoPneuFurado: '',
  descricaoPneuFurado: '',
  avariasCabine: false,
  descricaoAvariasCabine: '',
  fotosAvariasCabine: '',
  bauPossuiAvarias: false,
  descricaoAvariasBau: '',
  fotosAvariasBau: '',
  funcionamentoParteEletrica: true,
  motivoParteEletricaRuim: '',
  fotosParteEletricaRuim: '',
  sugestao: 'Inspeção realizada com sucesso.',
  userId: '',
  vehicleId: ''
}
/*export const initialFormState: VehicleInspectionForm = {
  crlvEmDia: false,
  fotoCRLV: "",
  certificadoTacografoEmDia: false,
  fotoTacografo: "",
  nivelAgua: "",
  fotoNivelAgua: "",
  nivelOleo: "",
  situacaoPneus: "",
  fotosPneusBom: "",
  motivoPneuRuim: "",
  fotosPneusRuim: "",
  pneuFurado: false,
  fotoPneuFurado: "",
  descricaoPneuFurado: "",
  avariasCabine: false,
  descricaoAvariasCabine: "",
  fotosAvariasCabine: "",
  bauPossuiAvarias: false,
  descricaoAvariasBau: "",
  fotosAvariasBau: "",
  funcionamentoParteEletrica: false,
  motivoParteEletricaRuim: "",
  fotosParteEletricaRuim: "",
  sugestao: "",
  vehicleId:"",
  userId:"",
};
*/